# https://docs.speedtest-tracker.dev/getting-started/installation/installation
# Speedtest Tracker

# This setup is for running in my Unraid server

version: "3.9"

x-base-env: &base-env
  PUID: ${PUID}
  PGID: ${PGID}
  UMASK: ${UMASK}
  TZ: ${TZ}

networks:
  speedtest-tracker-net:
    name: speedtest-tracker-net
    ipam:
      driver: default

services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    container_name: ${CONTAINER_NAME:-speedtest-tracker}
    restart: unless-stopped
    networks:
      - speedtest-tracker-net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA}:/config
      - ${APP_DATA}/web:/etc/ssl/web
    ports:
      # - 8080:80
      - 8443:443
    environment:
      <<: *base-env
      DB_CONNECTION: mysql
      DB_HOST: speedtest-tracker-db
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedy
      DB_PASSWORD: password
      APP_KEY: base64:ZGi2DOcRS0ZeaZu3rokNc7Degw7vzyAiU3mzlB8iVNY=
      FORCE_HTTPS: true
    depends_on:
      - speedtest-tracker-db

  speedtest-tracker-db:
    image: mariadb:10
    container_name: speedtest-tracker-db
    restart: always
    networks:
      - speedtest-tracker-net
    environment:
      MARIADB_DATABASE: speedtest_tracker
      MARIADB_USER: speedy
      MARIADB_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - speedtest-tracker-db:/var/lib/mysql

volumes:
  speedtest-tracker-db:
    name: speedtest-tracker-db
