# https://docs.plant-it.org/0.7.3/server-installation/
# plant-it

# This setup is for running in my Unraid server

version: "3.9"

x-base-env: &base-env
  PUID: ${PUID}
  PGID: ${PGID}
  UMASK: ${UMASK}
  TZ: ${TZ}

# include:
#   - networks.yml
networks:
  plant-it:
    name: plant-it
    ipam:
      config:
        - subnet: 10.2.8.0/24

name: plant-it
services:
  plant-it-server:
    image: msdeluise/plant-it-server:latest
    container_name: plant-it-server
    networks:
      - plant-it
    env_file: server.env
    depends_on:
      - plant-it-db
      - plant-it-cache
    restart: unless-stopped
    volumes:
      - ${APPDATA_BASE_PATH}/plant-it/upload-dir:/upload-dir
      - ${APPDATA_BASE_PATH}/plant-it/certs:/certificates
    ports:
      - ${API_PORT}:8080
      - ${HTTP_PORT}:3000
    environment:
      <<: *base-env
      TREFLE_KEY: ${TREFLE_KEY}

  plant-it-db:
    image: mysql:8.0
    container_name: plant-it-db
    networks:
      - plant-it
    restart: always
    env_file: server.env
    volumes:
      - ${APPDATA_BASE_PATH}/plant-it/db:/var/lib/mysql
    environment:
      <<: *base-env

  plant-it-cache:
    image: redis:7.2.1
    container_name: plant-it-cache
    networks:
      - plant-it
    restart: always
    environment:
      <<: *base-env
