# https://github.com/go-gitea/gitea
# Gitea

x-base-env: &base-env
  TZ: ${TZ:-Europe/London}
  UID: ${UID}
  GID: ${GID}
  PUID: ${UID}
  PGID: ${GID}
  UMASK: ${UMASK:-022}

name: ${CONTAINER_NAME:-gitea}

networks:
  default:
    name: ${CONTAINER_NAME:-gitea}
    ipam:
      config:
        - subnet: ${SUBNET:-10.42.0.0/24}

services:
  server:
    image: docker.gitea.com/gitea:${IMAGE_VERSION:-1}
    container_name: ${CONTAINER_NAME:-gitea}
    hostname: ${CONTAINER_NAME:-gitea}
    restart: always
    networks:
      - default
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-gitea}/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HTTP_PORT:-3000}:3000
    environment:
      <<: *base-env
      USER_UID: ${UID}
      USER_GID: ${GID}
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: ${DB_NAME:-gitea}
      GITEA__database__USER: ${DB_USER:-gitea}
      GITEA__database__PASSWD: ${DB_PASSWORD:-gitea}
      GITEA__security__INSTALL_LOCK: ${INSTALL_LOCK:-false}
      GITEA__server__ROOT_URL: ${ROOT_URL:-}
      GITEA__service__REQUIRE_SIGNIN_VIEW: ${REQUIRE_SIGNIN_VIEW:-true}
      GITEA__service__DISABLE_REGISTRATION: ${DISABLE_REGISTRATION:-true}
    depends_on:
      - db
    labels:
      - "com.service=${CONTAINER_NAME:-gitea}"

  db:
    image: postgres:${POSTGRES_VERSION:-14}
    container_name: ${CONTAINER_NAME:-gitea}_db
    hostname: ${CONTAINER_NAME:-gitea}_db
    restart: always
    networks:
      - default
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-gitea}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-gitea}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-gitea}
      POSTGRES_DB: ${DB_NAME:-gitea}
    labels:
      - "com.service=${CONTAINER_NAME:-gitea}_db"

  runner:
    image: gitea/act_runner:${RUNNER_VERSION:-latest}
    container_name: ${CONTAINER_NAME:-gitea}_runner
    hostname: ${CONTAINER_NAME:-gitea}_runner
    restart: always
    entrypoint: ["/entrypoint.sh"]
    networks:
      - default
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-gitea}/runner:/data
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ./runner-config.yaml:/config.template.yaml:ro
      - ./runner-entrypoint.sh:/entrypoint.sh:ro
    environment:
      TZ: ${TZ:-Europe/London}
      RUNNER_NETWORK: ${CONTAINER_NAME:-gitea}
      GITEA_INSTANCE_URL: http://server:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: ${RUNNER_REGISTRATION_TOKEN:-}
    depends_on:
      - server
    labels:
      - "com.service=${CONTAINER_NAME:-gitea}_runner"
