# Handbrake
# https://github.com/jlesage/docker-handbrake

x-base-env: &base-env
  PUID: ${UID:-1000}
  PGID: ${GID:-1000}
  UID: ${UID:-1000}
  GID: ${GID:-1000}
  UMASK: ${UMASK:-022}
  TZ: ${TZ:-Europe/London}

name: ${CONTAINER_NAME:-handbrake}

networks:
  default:
    name: ${CONTAINER_NAME:-handbrake}
    ipam:
      config:
        - subnet: ${SUBNET:-10.42.0.0/24}

services:
  handbrake:
    image: jlesage/handbrake
    container_name: ${CONTAINER_NAME:-handbrake}
    hostname: ${CONTAINER_NAME:-handbrake}
    restart: always
    networks:
      - default
    ulimits:
      core: ${ULIMIT_CORE:-0} # -1 on unRAID systems
    devices:
      - "${INTEL_GPU:-/dev/null}:/dev/dri" # Hardware Acceleration - Intel
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-handbrake}:/config:rw
      - ${STORAGE_PATH:/tmp}:/storage:ro # Contains files from the host that need to be accessible to the application.
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-handbrake}/watch:/watch:rw
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-handbrake}/output:/output:rw
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-handbrake}/trash:/trash:rw
    ports:
      - ${HTTP_PORT:-5800}:5800
      - ${VNC_PORT:-5900}:5900
    environment:
      <<: *base-env
      USER_ID: ${UID}
      GROUP_ID: ${GID}
      LANG: ${LANG:-en_AU.UTF-8}
      KEEP_APP_RUNNING: 1
      WEB_AUDIO: 1
      WEB_FILE_MANAGER: 1
      WEB_FILE_MANAGER_ALLOWED_PATHS: "/config,/storage,/watch,/output,/trash" # AUTO or comma seperated list
      WEB_AUTHENTICATION: ${WEB_AUTHENTICATION:-0}
      HANDBRAKE_GUI: 1
    labels:
      - "com.service=${CONTAINER_NAME:-handbrake}"