version: "3.9"

x-base-env: &base-env # Unraid
  PUID: ${UID}
  PGID: ${GID}
  UMASK: ${UMASK}
  TZ: ${TZ}

services:
  flaresolverr:
    image: flaresolverr/flaresolverr:${FLARESOLVERR_VERSION:-latest}
    restart: always
    # network_mode: "service:gluetun"
    networks:
      - media-net
    # ports:
    #   - ${FLARESOLVERR_HTTP_PORT:-8191}:8191
    environment:
      <<: *base-env
      TEST_URL: https://www.wikipedia.org
    deploy:
      replicas: 3