# Gluetun VPN client
# https://github.com/qdm12/gluetun

x-base-env: &base-env
  TZ: ${TZ:-Europe/London}
  PUID: ${UID}
  PGID: ${GID}
  UMASK: ${UMASK}

# https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
x-vpn: &vpn
  VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}

# https://github.com/qdm12/gluetun-wiki/blob/main/setup/wireguard.md
# https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/wireguard.md
x-wireguard: &wireguard
  VPN_TYPE: wireguard
  WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
  WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES} # xx.xx.xx.xx/xx
  # WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP}
  WIREGUARD_ENDPOINT_PORT: ${WIREGUARD_ENDPOINT_PORT:-51820}
  # WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: ${WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL}

# https://www.vpngids.nl/privacy/anoniem-browsen/5-eyes-9-eyes-14-eyes/
# https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#list-of-vpn-servers
# docker run --rm -v ${APPDATA_BASE_PATH}/gluetun:/gluetun qmcgaw/gluetun format-servers -mullvad # List of VPN servers
x-servers: &servers
  # SERVER_COUNTRIES: # Comma separated list of countries
  SERVER_COUNTRIES: Denmark,Finland,France,Germany,Netherlands,Norway,Sweden,Switzerland,UK # wireguard owned
  # SERVER_COUNTRIES: Australia,Brazil,Canada,Chile,Colombia,Israel,Mexico,New Zealand,Peru,USA # wireguard outside europe rented
  # SERVER_COUNTRIES: Hong Kong,Indonesia,Japan,Singapore,South Africa,Thailand # wireguard asia rented
  SERVER_CITIES: ${SERVER_CITIES}
  SERVER_HOSTNAMES: ${SERVER_HOSTNAMES}
  ISP: ${ISP}
  OWNED_ONLY: ${OWNED_ONLY:-no} # no,yes

# https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/control-server.md
# https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md
x-control-server: &control-server
  HTTP_CONTROL_SERVER_ADDRESS: ${HTTP_CONTROL_SERVER_ADDRESS:-:8000}
  HTTP_CONTROL_SERVER_LOG: ${HTTP_CONTROL_SERVER_LOG:-on} # on,off
  HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: ${HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH}

# https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/dns.md
x-dns: &dns
  DOT: ${DOT:-on} # on,off
  DOT_PROVIDERS: ${DOT_PROVIDERS:-quad9} # cloudflare, google, quad9, quadrant, cleanbrowsing
  DOT_CACHING: ${DOT_CACHING:-on}
  DNS_UPDATE_PERIOD: ${DNS_UPDATE_PERIOD:-24h}
  BLOCK_MALICIOUS: ${BLOCK_MALICIOUS:-on}
  BLOCK_SURVEILLANCE: ${BLOCK_SURVEILLANCE:-on}
  BLOCK_ADS: ${BLOCK_ADS:-on}
  UNBLOCK: ${UNBLOCK}

x-healthcheck: &healthcheck
  HEALTH_TARGET_ADDRESS: ${HEALTH_TARGET_ADDRESS:-cloudflare.com:443}	# Address to ping on every internal health check
  HEALTH_VPN_DURATION_INITIAL: 6s	# Initial duration to wait for the VPN to be ready before restarting it
  HEALTH_VPN_DURATION_ADDITION: 5s # Additional duration to add to the wait time for each consecutive failure of the VPN
  HEALTH_SUCCESS_WAIT_DURATION: 5s # Duration to wait after a success check to perform another check
  HEALTH_SERVER_ADDRESS: 127.0.0.1:9999 # Internal health check server listening address

# https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/others.md
x-others: &others
  PUBLICIP_ENABLED: ${PUBLICIP_ENABLED:-true}
  PUBLICIP_API: ${PUBLICIP_API:-ip2location}	# ipinfo, ip2location, cloudflare or custom URL
  VERSION_INFORMATION: ${VERSION_INFORMATION:-on} # on,off

# https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/updater.md
x-updater: &updater
  UPDATER_PERIOD: ${UPDATER_PERIOD:-24h}

services:
  gluetun:
    image: qmcgaw/gluetun:${GLUETUN_VERSION:-latest}
    # image: ghcr.io/qdm12/gluetun
    # container_name: ${NAME_PREFIX:-gluetun}
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    restart: always
    networks:
      - default
    cap_add:
      - NET_ADMIN
      - SYS_MODULE # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/wireguard.md
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # control-server
      # Transmission ports
      - ${TRANSMISSION_HTTP_PORT:-9091}:9091 # WebUI
      - ${TRANSMISSION_TORRENT_PORT:-51413}:51413 # Torrent Port TCP
      - ${TRANSMISSION_TORRENT_PORT:-51413}:51413/udp # Torrent Port UDP
      # Transmission Lat-Team
      - ${TRANSMISSION_LATTEAM_HTTP_PORT:-9092}:9092 # WebUI
      - ${TRANSMISSION_LATTEAM_TORRENT_PORT:-51414}:51414 # Torrent Port TCP
      - ${TRANSMISSION_LATTEAM_TORRENT_PORT:-51414}:51414/udp # Torrent Port UDP
      # Prowlarr
      # - ${PROWLARR_HTTP_PORT:-9696}:9696
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME_PREFIX:-media}/containers/gluetun:/gluetun
      - ./gluetun-auth-config.toml:/gluetun/auth/config.toml:ro
      - /lib/modules:/lib/modules:ro # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/wireguard.md
    environment:
      <<: [*base-env, *vpn, *wireguard, *servers, *control-server, *dns, *healthcheck, *others, *updater]
    labels:
      - "com.service=${CONTAINER_NAME_PREFIX:-media}-gluetun"