# Jellyseerr
# https://docs.jellyseerr.dev/getting-started/docker?docker-methods=docker-compose

x-base-env: &base-env
  TZ: ${TZ:-Europe/London}

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:${JELLYSEERR_VERSION:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-media}-jellyseerr
    hostname: ${CONTAINER_NAME_PREFIX:-media}-jellyseerr
    restart: always
    networks:
      - default
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME_PREFIX:-media}/containers/jellyseerr:/app/config
    ports:
      - ${JELLYSEERR_HTTP_PORT:-5055}:5055
    environment:
      <<: *base-env
      PORT: 5055
      DB_TYPE: sqlite
      # LOG_LEVEL: debug
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    labels:
      - "com.service=${CONTAINER_NAME_PREFIX:-media}-jellyseerr"