# PufferPanel
# https://www.pufferpanel.com/

# This setup is for running in my Unraid server

version: "3.9"

x-base-env: &base-env
  PUID: ${PUID}
  PGID: ${PGID}
  UMASK: ${UMASK}
  TZ: ${TZ}

networks:
  pufferpanel:
    name: pufferpanel
    ipam:
      config:
        - subnet: 10.33.34.0/24

services:
  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    container_name: pufferpanel
    networks:
      - pufferpanel
    restart: on-failure
    volumes:
      - ${APPDATA_BASE_PATH}/pufferpanel/config:/etc/pufferpanel
      - ${APPDATA_BASE_PATH}/pufferpanel/data:/var/lib/pufferpanel
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${HTTP_PORT}:8080
      - ${SFTP_PORT}:5657
    environment:
      <<: *base-env
      UID: ${PUID}
      GID: ${PGID}