# Portainer

# This is a template

x-base-env: &base-env
  TZ: ${TZ:-Europe/London}

name: ${CONTAINER_NAME:-portainer}

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${CONTAINER_NAME:-portainer}
    hostname: ${CONTAINER_NAME:-portainer}
    restart: always
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-portainer}:/data
    ports:
      - ${HTTPS_PORT:-9443}:9443/tcp
    environment:
      <<: *base-env
    labels:
      - "com.service=${CONTAINER_NAME:-portainer}"
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-false}"
