# https://hub.docker.com/r/linuxserver/bazarr

x-base-env: &base-env
  TZ: ${TZ:-Europe/London}
  PUID: ${UID}
  PGID: ${GID}
  UMASK: ${UMASK}

services:
  # Movies HD & Series HD
  bazarr-hd:
    image: lscr.io/linuxserver/bazarr:${BAZARR_VERSION:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-media}-bazarr-hd
    hostname: ${CONTAINER_NAME_PREFIX:-media}-bazarr-hd
    restart: always
    networks:
      - default
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME_PREFIX:-media}/containers/bazarr-hd:/config
      - ${MEDIA_PATH}/movies-hd:/movies
      - ${MEDIA_PATH}/series-hd:/tv
    ports:
      - ${BAZARR_HTTP_PORT:-6767}:6767 # WebUI
    environment:
      <<: *base-env
    labels:
      - "com.service=${CONTAINER_NAME_PREFIX:-media}-bazarr-hd"

  # Anime Movies/Series Subtitles
  bazarr-anime-hd:
    image: lscr.io/linuxserver/bazarr:${BAZARR_VERSION:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-media}-bazarr-anime
    hostname: ${CONTAINER_NAME_PREFIX:-media}-bazarr-anime
    restart: always
    networks:
      - default
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME_PREFIX:-media}/containers/bazarr-anime-hd:/config
      - ${MEDIA_PATH}/movies-anime-hd:/movies
      - ${MEDIA_PATH}/series-anime-hd:/tv
    ports:
      - ${BAZARR_ANIME_HTTP_PORT:-6768}:6767 # WebUI
    environment:
      <<: *base-env
    labels:
      - "com.service=${CONTAINER_NAME_PREFIX:-media}-bazarr-anime-hd"
