# https://github.com/searxng/searxng/tree/master/container
# SearXNG

x-base-env: &base-env
  TZ: ${TZ:-Europe/London}

name: ${CONTAINER_NAME:-searxng}

networks:
  default:
    name: ${CONTAINER_NAME:-searxng}
    ipam:
      config:
        - subnet: ${SUBNET:-10.42.0.0/24}

services:
  searxng:
    image: docker.io/searxng/searxng:${IMAGE_VERSION:-latest}
    container_name: ${CONTAINER_NAME:-searxng}
    hostname: ${CONTAINER_NAME:-searxng}
    restart: always
    networks:
      - default
    ports:
      - "${HTTP_PORT:-8080}:8080"
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME:-searxng}:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      <<: *base-env
      SEARXNG_BASE_URL: https://${SEARXNG_HOSTNAME:-localhost}/
      SEARXNG_PORT: ${SEARXNG_PORT:-8080}
      GRANIAN_BLOCKING_THREADS: ${GRANIAN_BLOCKING_THREADS:-4}
      SEARXNG_LIMITER: ${SEARXNG_LIMITER:-true}
      SEARXNG_PUBLIC_INSTANCE: ${SEARXNG_PUBLIC_INSTANCE:-true}
      SEARXNG_IMAGE_PROXY: ${SEARXNG_IMAGE_PROXY:-true}
      SEARXNG_METHOD: ${SEARXNG_METHOD:-POST}
      SEARXNG_STATIC_USE_HASH: ${SEARXNG_STATIC_USE_HASH:-true}
    depends_on:
      valkey:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      - "com.service=${CONTAINER_NAME:-searxng}"

  valkey:
    image: docker.io/valkey/valkey:${VALKEY_IMAGE_VERSION:-9-alpine}
    command: valkey-server --save 30 1 --loglevel warning
    container_name: ${CONTAINER_NAME_VALKEY:-searxng-valkey}
    hostname: ${CONTAINER_NAME_VALKEY:-searxng-valkey}
    restart: always
    networks:
      - default
    volumes:
      - valkey-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      - "com.service=${CONTAINER_NAME_VALKEY:-searxng-valkey}"

volumes:
  valkey-data:
  searxng-data:
