# Enable/Disable Watchtower

services:
  searxng:
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-false}"

  valkey:
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-false}"
